# Generated by Django 3.0 on 2019-12-27 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_like_dislike'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like_Dislike',
        ),
    ]
