# Generated by Django 2.2.7 on 2019-12-23 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='number',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
